apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: rpi
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
    elemental:
      install:
        reboot: true
        device-selector:
          - key: Name
            operator: In
            values:
              - /dev/sda
              - /dev/vda
              - /dev/nvme0
              - /dev/mmcblk0
        debug: true
        disable-boot-entry: true
      registration:
        emulate-tpm: true
      reset:
        debug: true
        enabled: true
        reset-persistent: true
        reset-oem: true
        poweroff: false
        reboot: true
  machineInventoryLabels:
    location: canada
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
