apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: rpi
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: "$6$/OBpzEc039L4Ovc3$xlXHWOm/LLarJB3mILq2IT9g3zr4aRtN6dB5M/RZfUmuaAPZkmo4L/vrJfvnhRPS23KD1NLB/SpOAErl00ShO/"
      write_files:
        - content: |
            OPTION1="yes"
            OPTION2="false"
          path: "/etc/myservice.conf"
      runcmd:
        - mkdir -p /usr/local/data
        - mount /dev/disk/by-label/EXTRA_PART /usr/local/data
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        disable-boot-entry: true
      registration:
        emulate-tpm: true
  machineInventoryLabels:
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
    registration: rpi
---
apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: kvm
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: "$6$/OBpzEc039L4Ovc3$xlXHWOm/LLarJB3mILq2IT9g3zr4aRtN6dB5M/RZfUmuaAPZkmo4L/vrJfvnhRPS23KD1NLB/SpOAErl00ShO/"
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        config-dir: /etc/elemental
  machineInventoryLabels:
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
    registration: kvm
