apiVersion: elemental.cattle.io/v1beta1
kind: MachineRegistration
metadata:
  name: rpi
  namespace: fleet-default
spec:
  config:
    cloud-config:
      users:
        - name: root
          passwd: root
      write_files:
        - content: |
            OPTION1="yes"
            OPTION2="false"
          path: "/etc/myservice.conf"
    elemental:
      install:
        reboot: true
        device: /dev/sda
        debug: true
        disable-boot-entry: true
      registration:
        emulate-tpm: true
  machineInventoryLabels:
    manufacturer: "${System Information/Manufacturer}"
    productName: "${System Information/Product Name}"
    serialNumber: "${System Information/Serial Number}"
    machineUUID: "${System Information/UUID}"
    registration: rpi
