apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: rpi
  namespace: fleet-default
spec:
  baseImage: https://artifacts.smartgic.io/elemental.raw
  size: 16106127360
  type: raw
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: rpi
    namespace: fleet-default
