apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: rpi
  namespace: fleet-default
spec:
  baseImage: ghcr.io/goldyfruit/rpi:latest
  targetPlatform: linux/arm64
  type: raw
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: rpi
    namespace: fleet-default
---
apiVersion: elemental.cattle.io/v1beta1
kind: SeedImage
metadata:
  name: kvm
  namespace: fleet-default
spec:
  baseImage: ghcr.io/goldyfruit/green:latest
  registrationRef:
    apiVersion: elemental.cattle.io/v1beta1
    kind: MachineRegistration
    name: kvm
    namespace: fleet-default
